module music2
(
    input           clk,
    input           rst, //SYS_RESET
    // Z80 
    output          SRDB,
    output          SWRB, 

    //PLD238 
    output          SEL6295, 

    // SEI080BU 
    // input 14.13Mhz ?
    input           N1H,
    input           N6M, 

    input           MUSIC, 
    input           MWRLB, // MAIN WRITE R? L? BUS
    input           MRDLB, // MAIN READ  D? L? BUS
    input   [3:1]   MAB, // MAIN ADDRESS BUS 
    input   [7:0]   MDB_CPU_OUT, // MAIN DATA BUS
    output  [7:0]   MDB_IN, // MAIN DATA BUS
    input           IRQ3812,
    input           COIN1,
    input           COIN2, 
    output          COUNTER1,
    output          COUNTER2, 
    output          CS3812,
    //74HC74
    output          CLK_3_6, 
    output          PRCLK1,
    output          SA_0, 
    output   [7:0]  SD_OUT,
    input     [7:0] MUSIC1_SD_IN,

    input             oki_cen, //XXX generated by sei0080bu
    /// ROM 
    input       [7:0] z80_rom_data,
    input             z80_rom_ok, 
    output     [12:0] z80_rom_addr,
    output            z80_rom_cs_n,

    input       [7:0] bank_rom_data,
    input             bank_rom_ok, 
    output     [15:0] bank_rom_addr,
    output            bank_rom_cs_n
);



///////// Z80 CPU  /////////////////////// 
// 
//
//
wire [7:0] SD_IN; //reg ?
wire z80_iorq_n;
wire z80_cen;
wire z80_busak_n;

wire RFSH_n;
wire Z80_INT;
wire [15:0] SA;

assign SA_0 = SA[0];
assign z80_rom_addr[12:0] = SA[12:0];
 //0x2000 first bytes
assign bank_rom_addr[15:0] = {BANK_SELECTED, SA[14:0]};

jtframe_z80 u_z80(
    .clk(clk),
    .cen(CLK_3_6),
    .rst_n(~rst),

    .wait_n(wait_n), //XXX was wait_n because of ROM like for 68k  
    .int_n(Z80_INT), //DRIVE BY CONTROLER PIN 23  // sound interrupt
    .nmi_n(1'b1),
    .busrq_n(1'b1),

    .m1_n(z80_m1_n),
    .mreq_n(z80_mreq_n),
    .iorq_n(z80_iorq_n),
    .rd_n(SRDB), 
    .wr_n(SWRB),
    .rfsh_n(RFSH_n), //ram refresh
    .halt_n(), 
    .busak_n(),

    .A(SA[15:0]),

    .din(SD_IN), //SD_IN ? 
    .dout(SD_OUT) //SD_OUT  XXX share bus with sei0100bu  
);

///// PLD 23 //////////////////////////
//
//  Chip select 
//
wire irq_ack_n;
wire SEI0100_CS_N, B1, z80_ram_cs_n;

pld23 pld23_u(
  .SA_3(SA[3]),
  .SA_13(SA[13]),
  .SA_14(SA[14]),
  .SA_15(SA[15]),
  .MEMRQ_n(z80_mreq_n),
  .IORQ_n(z80_iorq_n),
  .RD_n(SRDB),
  .RFSH_n(RFSH_n),
  .M1_n(z80_m1_n),

  .SEI0100_CS_N(SEI0100_CS_N), //-> SEI0100BU addrs ? XXX 41 
  .B1(B1), // -> SEU100BU addrs ? XXX 48 
  .SEL6295(SEL6295),
  .irq_ack_n(irq_ack_n), // SEI0100BU ? XXX 54 
  .bank_rom_cs_n(bank_rom_cs_n), // EPROM CE Z80 64k / (CS) 
  .z80_ram_cs_n(z80_ram_cs_n), // Z80 RAM CS      
  .z80_rom_cs_n(z80_rom_cs_n) // SEI080 BU ? XXX addrs cs ? 
);

////// Z80 RAM  ///////////////////////
//
//  2kx8bits ram  (2048)
//
wire [7:0] RAM_SD_OUT;

//jtframe_ram #(.AW(11), .CEN_RD(1)) u_z80_cpu_ram( ///XXX CLOCK ENABLE ?
jtframe_ram #(.AW(11)) u_z80_cpu_ram( ///XXX CLOCK ENABLE ?
    .clk(clk),
    .cen(CLK_3_6), //CEN 3_6   & ram_cs ? 
    .data(SD_OUT[7:0]),
    .addr(SA[10:0]),  //z80_addr 
    .we(~z80_ram_cs_n & ~SWRB), //PLD23 19
    .q(RAM_SD_OUT[7:0])
);

///// SEI0100BU ////////////////////////////
//
// 2151/5205 controller 
// YM3931 (SDIP64)

wire [7:0] SEI0100_SD_IN;

wire irq_rst10, irq_rst18, main_data_pending_cs, sub2main_pending,
  read_coin_cs, m68k_latch0_cs, m68k_latch1_cs, BANK_SELECTED;

sei0100bu sei0100bu_u(
  .clk(clk),
  .rst(rst),
  .MUSIC(MUSIC),
  .MWRLB(MWRLB),
  .MRDLB(MRDLB),
  .MAB(MAB),  
  .MDB_OUT(MDB_CPU_OUT),
  .MDB_IN(MDB_IN),
  .irq_ack_n(irq_ack_n),
  .IRQ3812(IRQ3812),
  .CLK_3_6(CLK_3_6),
  .COIN1(COIN1),
  .COIN2(COIN1),
  .SEI0100_CS_N(SEI0100_CS_N),
  .SWRB(SWRB),
  .B1(B1),
  .SA(SA[4:0]), //32 + sei0100_cs => z80_cs selection 
   // output 
  .COUNTER1(COUNTER1),
  .COUNTER2(COUNTER1),
  .Z80_INT(Z80_INT),
  .CS3812(CS3812),
  .SD_OUT(SD_OUT),
  .SD_IN(SEI0100_SD_IN),
  .BANK_SELECTED(BANK_SELECTED)
); 

// simulate shared bus
assign SD_IN =  
                 ~CS3812 & ~SRDB                       ? MUSIC1_SD_IN :   
                 ~SEL6295 & ~SRDB                      ? MUSIC1_SD_IN :
                 // XXX ORDER SEEMS IMPORTANT ?? WHY ? 
                 ~SEI0100_CS_N ? SEI0100_SD_IN :
                 ~irq_ack_n ? SEI0100_SD_IN :
                 //we need to read data from main and main need to read our
                 ~z80_ram_cs_n                            ? RAM_SD_OUT:
                 ~bank_rom_cs_n                           ? bank_rom_data :
                 ~z80_rom_cs_n                            ? decrypt_rom_data :
                                                            8'hff;

///////// SEIBU80 //////////
//
// Decypher z80 ROM 8.m3
//
wire [7:0] decrypt_rom_data;
//wire       decrypt_rom_ok;
reg        decrypt_rom_cs_seibu;

wire       z80_m1_n;   //m1 low => opcode
wire       z80_mreq_n;

sei80bu u_sei80bu(
  //N1H ?? ~hpos[0] ?/
  .clk(clk),
  .N1H(N1H),
  .N6M(N6M),
  .z80_rom_addr({3'd0, z80_rom_addr}),
  .z80_rom_data(z80_rom_data),
  .z80_rom_ok(z80_rom_ok), 
  .z80_rom_cs_n(z80_rom_cs_n),
  .z80_m1(~z80_m1_n),
  .decrypt_rom_data(decrypt_rom_data),
  //.decrypt_rom_ok(decrypt_rom_ok),
  .oki_cen(oki_cen),
  .PRCLK1(PRCLK1),
  .CLK_3_6(CLK_3_6)
);

///////// Z80 WAIT ///////////////////////
// 
// make z80 bus wait if rom or banked rom
// is selected and not available  
// 
//

/// XXX NEEDED ONLY BECAUE OF SDRAM ? NOT ON ORIGINAL BOARD
reg wait_n;

always @(posedge clk) begin
  if (rst)
    wait_n <= 1'b1;
  //else if (CLK_3_6) begin
  else begin
    if (~z80_rom_cs_n & ~z80_rom_ok)
      wait_n <= 1'b0;
    else if (~bank_rom_cs_n & ~bank_rom_ok)
      wait_n <= 1'b0;
    else 
      wait_n <= 1'b1;
  end 
end

endmodule 
